@startuml
title WarmHouse Device Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseSystem, "WarmHouse System") {
  Container(DeviceManagement, "Device Management", "Python, FastAPI", "Device lifecycle management, telemetry and monitoring")
  ContainerDb(DeviceDB, "Device database", "PostgreSQL", "Stores device data")
}

Container(DeviceManagement, "Device Management", "Python, FastAPI") {
  Component(DeviceControlAPI, "Device control API", "Handles incoming API requests and sends command to device")
  Component(DeviceRegistrationController, "Device Registration Controller", "Allows user to connect device")
  Component(DeviceConfigController, "Device Configuration Controller", "Allows user configuration device")
  Component(MonitoringController, "Device Monitoring Controller", "Allows user fetch monitoring data")
  Component(MonitoringService, "DeviceMonitoring Service", "Business logic for Monitoring")
  Component(TelemetryIngestionService, "Device Telemetry Ingestion Service", "Business logic for telemetry")
  Component(DeviceProvisioningService, "Device Provisioning Service", "Business logic for provisioning")
  Component(DeviceConfigService, "Device Configuration Service", "Business logic for settings, location, etc.")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

System_Ext(api, "Third-Party API", "External API for device onboarding and fetch telemetry")
System_Ext(messageQueue, "Message Queue", "Transports telemetry events for async processing")


Rel(DeviceRegistrationController,DeviceProvisioningService,"Calls business logic")
Rel(DeviceConfigController,DeviceConfigService,"Calls business logic")
Rel(MonitoringController, MonitoringService,"Calls business logic")
Rel(MonitoringService, RepositoryLayer,"Reads/Writes data")
Rel(DeviceProvisioningService,RepositoryLayer,"Reads/Writes data")
Rel(DeviceConfigService,RepositoryLayer,"Reads/Writes data")
Rel(TelemetryIngestionService,RepositoryLayer,"Reads/Writes data")
Rel(TelemetryIngestionService,messageQueue,"Kafka Topics")
Rel(RepositoryLayer,DeviceDB,"Reads/Writes user data")
Rel(TelemetryIngestionService,api,"Makes API calls to")
Rel(DeviceProvisioningService,api,"Makes API calls to")
Rel(DeviceControlAPI,api,"Makes API calls to")
@enduml