
services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  temperature-api:
    build: ./temperature-api
    container_name: temperature-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  device-service:
    build: ./device-service
    container_name: device-service
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    networks:
      - smarthome-network

  telemetry-service:
    build: ./telemetry-service
    container_name: telemetry-service
    ports:
      - "8083:8080"
    depends_on:
      temperature-api:
        condition: service_started
    restart: unless-stopped
    environment:
      - TEMPERATURE_API_URL=http://temperature-api:8081
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge